[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x5b5858"
blue = "0x3fc4de"
cyan = "0x6be4e6"
green = "0x3fdaa4"
magenta = "0xf075b5"
red = "0xec6a88"
white = "0xd5d8da"
yellow = "0xfbc3a7"

[colors.normal]
black = "0x16161c"
blue = "0x26bbd9"
cyan = "0x59e1e3"
green = "0x29d398"
magenta = "0xee64ac"
red = "0xe95678"
white = "0xd5d8da"
yellow = "0xfab795"

[colors.primary]
background = "0x1c1e26"
foreground = "0xe0e0e0"

[cursor.style]
blinking = "Off"
shape = "Beam"

[font]
size = 7.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

### EXTRA COLOR SCHEMES
#
#
# [schemes.Darcula.bright]
# black = "0x282a35"
# blue = "0xcaa9fa"
# cyan = "0x9aedfe"
# green = "0x5af78e"
# magenta = "0xff92d0"
# red = "0xff6e67"
# white = "0xe6e6e6"
# yellow = "0xf4f99d"
#
# [schemes.Darcula.normal]
# black = "0x000000"
# blue = "0xcaa9fa"
# cyan = "0x8be9fd"
# green = "0x50fa7b"
# magenta = "0xff79c6"
# red = "0xff5555"
# white = "0xbfbfbf"
# yellow = "0xf1fa8c"
#
# [schemes.Darcula.primary]
# background = "0x282a36"
# foreground = "0xf8f8f2"
#
# [schemes.HorizonDark.bright]
# black = "0x5b5858"
# blue = "0x3fc4de"
# cyan = "0x6be4e6"
# green = "0x3fdaa4"
# magenta = "0xf075b5"
# red = "0xec6a88"
# white = "0xd5d8da"
# yellow = "0xfbc3a7"
#
# [schemes.HorizonDark.normal]
# black = "0x16161c"
# blue = "0x26bbd9"
# cyan = "0x59e1e3"
# green = "0x29d398"
# magenta = "0xee64ac"
# red = "0xe95678"
# white = "0xd5d8da"
# yellow = "0xfab795"
#
# [schemes.HorizonDark.primary]
# background = "0x1c1e26"
# foreground = "0xe0e0e0"
#
# [schemes.Palenight.bright]
# black = "0x434758"
# blue = "0x9cc4ff"
# cyan = "0xa3f7ff"
# green = "0xddffa7"
# magenta = "0xe1acff"
# red = "0xff8b92"
# white = "0xffffff"
# yellow = "0xffe585"
#
# [schemes.Palenight.normal]
# black = "0x292d3e"
# blue = "0x82aaff"
# cyan = "0x89ddff"
# green = "0xc3e88d"
# magenta = "0xc792ea"
# red = "0xf07178"
# white = "0xd0d0d0"
# yellow = "0xffcb6b"
#
# [schemes.Palenight.primary]
# background = "0x292d3e"
# foreground = "0xd0d0d0"
#
# [schemes.Snazzy.bright]
# black = "#686868"
# blue = "#57c7ff"
# cyan = "#9aedfe"
# green = "#5af78e"
# magenta = "#ff6ac1"
# red = "#ff5c57"
# white = "#f1f1f0"
# yellow = "#f3f99d"
#
# [schemes.Snazzy.normal]
# black = "#282a36"
# blue = "#57c7ff"
# cyan = "#9aedfe"
# green = "#5af78e"
# magenta = "#ff6ac1"
# red = "#ff5c57"
# white = "#f1f1f0"
# yellow = "#f3f99d"
#
# [schemes.Snazzy.primary]
# background = "#282a36"
# foreground = "#eff0eb"
#
#
#
### END OF EXTRA COLOR SCHEMES ###

[window]
opacity = 0.9

[window.padding]
x = 3
y = 3
